[project]
name = "moong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.10",
    "django>=6.0.1",
    "openai>=2.15.0",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
]
